/*
 * Copyright (c) 2017 Jon Szymaniak <jon.szymaniak@gmail.com>
 * SPDX License Identifier: GPL-3.0
 *
 * Common command-line flag definitions
 */
package common

const (
	FLAG_PROJECT       = "project"
	FLAG_PROJECT_DESC  = "Project file to work with. (This is the file generated by reid-enxml.)"
	FLAG_PROJECT_SHORT = 'p'

	FLAG_DEBUG      = "debug"
	FLAG_DEBUG_DESC = "Enable diagnostic output"

	FLAG_VERBOSE      = "verbose"
	FLAG_VERBOSE_DESC = "Enable extra verbose diagnostic output"
)
