/*
 * Copyright (c) 2017 Jon Szymaniak <jon.szymaniak@gmail.com>
 * SPDX License Identifier: GPL-3.0
 *
 * Common command-line flag definitions
 */
package common

import (
	"fmt"
	"os"

	"gopkg.in/alecthomas/kingpin.v2"

	"../../reid"
)

const (
	FLAG_PROJECT       = "project"
	FLAG_PROJECT_DESC  = "Project file to work with. (This is the file generated by reid-enxml.)"
	FLAG_PROJECT_SHORT = 'p'

	FLAG_DEBUG      = "debug"
	FLAG_DEBUG_DESC = "Enable diagnostic output."

	FLAG_VERBOSE      = "verbose"
	FLAG_VERBOSE_DESC = "Enable extra verbose diagnostic output."

	FLAG_VERSION      = "version"
	FLAG_VERSION_DESC = "Print the program version and exit."
)

func ParseCommandLine() string {
	for _, arg := range os.Args {
		if arg == "--version" {
			fmt.Println(reid.Version.String())
			os.Exit(0)
		}
	}

	return kingpin.Parse()
}
